(function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};g.Symbol||(g.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function l(){k();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){l();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}
function n(a){if(!(a instanceof Array)){l();var b=a[Symbol.iterator];a=b?b.call(a):m(a);for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function fa(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
var p=window.Element.prototype,ha=p.matches||p.matchesSelector||p.webkitMatchesSelector||p.mozMatchesSelector||p.msMatchesSelector||p.oMatchesSelector;function ia(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||ja(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||ja(a,d))return!0}return!1}function ja(a,b){if("string"!=typeof b)return!1;if(ha)return ha.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}
function ka(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function la(a,b,c){function d(a){var d;if(h.composed&&"function"==typeof a.composedPath)for(var e=a.composedPath(),f=0,D;D=e[f];f++)1==D.nodeType&&ia(D,b)&&(d=D);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(ka(d)),e=0;f=d[e];e++)if(ia(f,b)){d=f;break a}d=void 0}d&&c.call(d,a,d)}var e=document,h={composed:!0,B:!0},h=void 0===h?{}:h;e.addEventListener(a,d,h.B);return{j:function(){e.removeEventListener(a,d,h.B)}}}
function ma(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(!a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var na=/:(80|443)$/,q=document.createElement("a"),r={};
function t(a){a=a&&"."!=a?a:location.href;if(r[a])return r[a];q.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return t(q.href);var b="80"==q.port||"443"==q.port?"":q.port,b="0"==b?"":b,c=q.host.replace(na,"");return r[a]={hash:q.hash,host:c,hostname:q.hostname,href:q.href,origin:q.origin?q.origin:q.protocol+"//"+c,pathname:"/"==q.pathname.charAt(0)?q.pathname:"/"+q.pathname,port:b,protocol:q.protocol,search:q.search}}var u=[];
function oa(a,b){var c=this;this.context=a;this.v=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.b=[];this.a=[];this.g=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.a[c.a.length-1].apply(null,[].concat(n(b)))};this.c?a.set(b,this.g):a[b]=this.g}function v(a,b,c){a=pa(a,b);a.b.push(c);qa(a)}function w(a,b,c){a=pa(a,b);c=a.b.indexOf(c);-1<c&&(a.b.splice(c,1),0<a.b.length?qa(a):a.j())}
function qa(a){a.a=[];for(var b,c=0;b=a.b[c];c++){var d=a.a[c-1]||a.f.bind(a.context);a.a.push(b(d))}}oa.prototype.j=function(){var a=u.indexOf(this);-1<a&&(u.splice(a,1),this.c?this.context.set(this.v,this.f):this.context[this.v]=this.f)};function pa(a,b){var c=u.filter(function(c){return c.context==a&&c.v==b})[0];c||(c=new oa(a,b),u.push(c));return c}
function x(a,b,c,d,e,h){if("function"==typeof d){var f=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,e,h);f(c)}}}return y({},a,b)}function ra(a,b){var c=ma(a),d={};Object.keys(c).forEach(function(a){if(!a.indexOf(b)&&a!=b+"on"){var e=c[a];"true"==e&&(e=!0);"false"==e&&(e=!1);a=sa(a.slice(b.length));d[a]=e}});return d}
function ta(a){var b;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];clearTimeout(b);b=setTimeout(function(){return a.apply(null,[].concat(n(d)))},500)}}function ua(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}var z={};
function va(a,b){function c(){clearTimeout(e.timeout);e.send&&w(a,"send",e.send);delete z[d];e.A.forEach(function(a){return a()})}var d=a.get("trackingId"),e=z[d]=z[d]||{};clearTimeout(e.timeout);e.timeout=setTimeout(c,0);e.A=e.A||[];e.A.push(b);e.send||(e.send=function(a){return function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c();a.apply(null,[].concat(n(d)))}},v(a,"send",e.send))}
var y=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var d=0,e=c.length;d<e;d++){var h=Object(c[d]),f;for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(a[f]=h[f])}return a};function sa(a){return a.replace(/[\-\_]+(\w?)/g,function(a,c){return c.toUpperCase()})}var A=function wa(b){return b?(b^16*Math.random()>>b/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,wa)};
function B(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}var C={K:1,C:2,L:3,M:4,N:5,F:6,G:7,O:8,H:9,D:10},E=Object.keys(C).length;
function F(a,b){a.set("\x26_av","2.4.1");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<E)for(var d=E-c.length;d;)c="0"+c,d--;b=E-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}
function G(a,b){var c=this;F(a,C.C);if(window.addEventListener){this.a=y({events:["click"],fieldsObj:{},attributePrefix:"ga-"},b);this.f=a;this.c=this.c.bind(this);var d="["+this.a.attributePrefix+"on]";this.b={};this.a.events.forEach(function(a){c.b[a]=la(a,d,c.c)})}}
G.prototype.c=function(a,b){var c=this.a.attributePrefix;if(!(0>b.getAttribute(c+"on").split(/\s*,\s*/).indexOf(a.type))){var c=ra(b,c),d=y({},this.a.fieldsObj,c);this.f.send(c.hitType||"event",x({transport:"beacon"},d,this.f,this.a.hitFilter,b,a))}};G.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].j()})};B("eventTracker",G);
function H(a,b){var c=this;F(a,C.F);window.addEventListener&&(this.a=y({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.c=a,this.f=this.f.bind(this),this.b={},this.a.events.forEach(function(a){c.b[a]=la(a,c.a.linkSelector,c.f)}))}
H.prototype.f=function(a,b){var c=this;if(this.a.shouldTrackOutboundLink(b,t)){var d=b.getAttribute("href")||b.getAttribute("xlink:href"),e=t(d),e={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:e.href},h=y({},this.a.fieldsObj,ra(b,this.a.attributePrefix)),f=x(e,h,this.c,this.a.hitFilter,b,a);if(navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which)this.c.send("event",f);else{var ea=function(){window.removeEventListener("click",
ea);if(!a.defaultPrevented){a.preventDefault();var b=f.hitCallback;f.hitCallback=ua(function(){"function"==typeof b&&b();location.href=d})}c.c.send("event",f)};window.addEventListener("click",ea)}}};H.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};H.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].j()})};B("outboundLinkTracker",H);
function I(a,b){F(a,C.H);history.pushState&&window.addEventListener&&(this.a=y({shouldTrackUrlChange:this.shouldTrackUrlChange,trackReplaceState:!1,fieldsObj:{},hitFilter:null},b),this.g=a,this.h=location.pathname+location.search,this.c=this.c.bind(this),this.f=this.f.bind(this),this.b=this.b.bind(this),v(history,"pushState",this.c),v(history,"replaceState",this.f),window.addEventListener("popstate",this.b))}
I.prototype.c=function(a){var b=this;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];a.apply(null,[].concat(n(d)));J(b,!0)}};I.prototype.f=function(a){var b=this;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];a.apply(null,[].concat(n(d)));J(b,!1)}};I.prototype.b=function(){J(this,!0)};
function J(a,b){setTimeout(function(){var c=a.h,d=location.pathname+location.search;c!=d&&a.a.shouldTrackUrlChange.call(a,d,c)&&(a.h=d,a.g.set({page:d,title:document.title}),(b||a.a.trackReplaceState)&&a.g.send("pageview",x({transport:"beacon"},a.a.fieldsObj,a.g,a.a.hitFilter)))},0)}I.prototype.shouldTrackUrlChange=function(a,b){return!(!a||!b)};I.prototype.remove=function(){w(history,"pushState",this.c);w(history,"replaceState",this.f);window.removeEventListener("popstate",this.b)};
B("urlChangeTracker",I);function xa(){this.a={}}function ya(a,b){(a.a.externalSet=a.a.externalSet||[]).push(b)}xa.prototype.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];(this.a[a]=this.a[a]||[]).forEach(function(a){return a.apply(null,[].concat(n(c)))})};var K={},L=!1,M;function N(a,b){b=void 0===b?{}:b;this.a={};this.b=a;this.m=b;this.i=null}fa(N,xa);
function O(a,b,c){a=["autotrack",a,b].join(":");K[a]||(K[a]=new N(a,c),L||(window.addEventListener("storage",za),L=!0));return K[a]}function P(){if(null!=M)return M;try{window.localStorage.setItem("autotrack","autotrack"),window.localStorage.removeItem("autotrack"),M=!0}catch(a){M=!1}return M}N.prototype.get=function(){if(this.i)return this.i;if(P())try{this.i=Q(window.localStorage.getItem(this.b))}catch(a){}return this.i=y({},this.m,this.i)};
N.prototype.set=function(a){this.i=y({},this.m,this.i,a);if(P())try{var b=JSON.stringify(this.i);window.localStorage.setItem(this.b,b)}catch(c){}};function R(a){a.i={};if(P())try{window.localStorage.removeItem(a.b)}catch(b){}}N.prototype.j=function(){delete K[this.b];Object.keys(K).length||(window.removeEventListener("storage",za),L=!1)};function za(a){var b=K[a.key];if(b){var c=y({},b.m,Q(a.oldValue));a=y({},b.m,Q(a.newValue));b.i=a;b.I("externalSet",a,c)}}
function Q(a){var b={};if(a)try{b=JSON.parse(a)}catch(c){}return b}var S={};function T(a,b,c){this.f=a;this.timeout=b||U;this.timeZone=c;this.b=this.b.bind(this);v(a,"sendHitTask",this.b);try{this.c=new Intl.DateTimeFormat("en-US",{timeZone:this.timeZone})}catch(d){}this.a=O(a.get("trackingId"),"session",{hitTime:0,isExpired:!1});this.a.get().id||this.a.set({id:A()})}function Aa(a,b,c){var d=a.get("trackingId");return S[d]?S[d]:S[d]=new T(a,b,c)}function V(a){return a.a.get().id}
T.prototype.isExpired=function(a){a=void 0===a?V(this):a;if(a!=V(this))return!0;a=this.a.get();if(a.isExpired)return!0;var b=a.hitTime;return b&&(a=new Date,b=new Date(b),a-b>6E4*this.timeout||this.c&&this.c.format(a)!=this.c.format(b))?!0:!1};T.prototype.b=function(a){var b=this;return function(c){a(c);var d=c.get("sessionControl");c="start"==d||b.isExpired();var d="end"==d,e=b.a.get();e.hitTime=+new Date;c&&(e.isExpired=!1,e.id=A());d&&(e.isExpired=!0);b.a.set(e)}};
T.prototype.j=function(){w(this.f,"sendHitTask",this.b);this.a.j();delete S[this.f.get("trackingId")]};var U=30,W=A();
function X(a,b){var c=this;F(a,C.G);document.visibilityState&&(this.a=y({sessionTimeout:U,visibleThreshold:5E3,sendInitialPageview:!1,fieldsObj:{}},b),this.b=a,this.h=document.visibilityState,this.s=null,this.w=!1,this.l=this.l.bind(this),this.f=this.f.bind(this),this.o=this.o.bind(this),this.u=this.u.bind(this),this.c=O(a.get("trackingId"),"plugins/page-visibility-tracker"),ya(this.c,this.u),this.g=Aa(a,this.a.sessionTimeout,this.a.timeZone),v(a,"set",this.l),window.addEventListener("unload",this.o),
document.addEventListener("visibilitychange",this.f),va(this.b,function(){if("visible"==document.visibilityState)c.a.sendInitialPageview&&(Y(c,{J:!0}),c.w=!0),c.c.set({time:+new Date,state:"visible",pageId:W,sessionId:V(c.g)});else if(c.a.sendInitialPageview&&c.a.pageLoadsMetricIndex){var a={},a=(a.transport="beacon",a.eventCategory="Page Visibility",a.eventAction="page load",a.eventLabel="(not set)",a["metric"+c.a.pageLoadsMetricIndex]=1,a.nonInteraction=!0,a);c.b.send("event",x(a,c.a.fieldsObj,
c.b,c.a.hitFilter))}}))}
X.prototype.f=function(){var a=this;if("visible"==document.visibilityState||"hidden"==document.visibilityState){var b=Ba(this),c={time:+new Date,state:document.visibilityState,pageId:W,sessionId:V(this.g)};"visible"==document.visibilityState&&this.a.sendInitialPageview&&!this.w&&(Y(this),this.w=!0);"hidden"==document.visibilityState&&this.s&&clearTimeout(this.s);this.g.isExpired(b.sessionId)?(R(this.c),"hidden"==this.h&&"visible"==document.visibilityState&&(clearTimeout(this.s),this.s=setTimeout(function(){a.c.set(c);
Y(a,{hitTime:c.time})},this.a.visibleThreshold))):(b.pageId==W&&"visible"==b.state&&Ca(this,b),this.c.set(c));this.h=document.visibilityState}};function Ba(a){var b=a.c.get();"visible"==a.h&&"hidden"==b.state&&b.pageId!=W&&(b.state="visible",b.pageId=W,a.c.set(b));return b}
function Ca(a,b,c){c=(c?c:{}).hitTime;var d={hitTime:c},d=(d?d:{}).hitTime;(b=b.time?(d||+new Date)-b.time:0)&&b>=a.a.visibleThreshold&&(b=Math.round(b/1E3),d={transport:"beacon",nonInteraction:!0,eventCategory:"Page Visibility",eventAction:"track",eventValue:b,eventLabel:"(not set)"},c&&(d.queueTime=+new Date-c),a.a.visibleMetricIndex&&(d["metric"+a.a.visibleMetricIndex]=b),a.b.send("event",x(d,a.a.fieldsObj,a.b,a.a.hitFilter)))}
function Y(a,b){var c=b?b:{};b=c.hitTime;var c=c.J,d={transport:"beacon"};b&&(d.queueTime=+new Date-b);c&&a.a.pageLoadsMetricIndex&&(d["metric"+a.a.pageLoadsMetricIndex]=1);a.b.send("pageview",x(d,a.a.fieldsObj,a.b,a.a.hitFilter))}X.prototype.l=function(a){var b=this;return function(c,d){var e={},e="object"==typeof c&&null!==c?c:(e[c]=d,e);e.page&&e.page!==b.b.get("page")&&"visible"==b.h&&b.f();a(c,d)}};
X.prototype.u=function(a,b){a.time!=b.time&&(b.pageId!=W||"visible"!=b.state||this.g.isExpired(b.sessionId)||Ca(this,b,{hitTime:a.time}))};X.prototype.o=function(){"hidden"!=this.h&&this.f()};X.prototype.remove=function(){this.c.j();this.g.j();w(this.b,"set",this.l);window.removeEventListener("unload",this.o);document.removeEventListener("visibilitychange",this.f)};B("pageVisibilityTracker",X);
function Z(a,b){F(a,C.D);window.addEventListener&&(this.b=y({increaseThreshold:20,sessionTimeout:U,fieldsObj:{}},b),this.f=a,this.c=Da(this),this.g=ta(this.g.bind(this)),this.l=this.l.bind(this),this.a=O(a.get("trackingId"),"plugins/max-scroll-tracker"),this.h=Aa(a,this.b.sessionTimeout,this.b.timeZone),v(a,"set",this.l),Ea(this))}function Ea(a){100>(a.a.get()[a.c]||0)&&window.addEventListener("scroll",a.g)}
Z.prototype.g=function(){var a=document.documentElement,b=document.body,a=Math.min(100,Math.max(0,Math.round(window.pageYOffset/(Math.max(a.offsetHeight,a.scrollHeight,b.offsetHeight,b.scrollHeight)-window.innerHeight)*100))),b=V(this.h);b!=this.a.get().sessionId&&(R(this.a),this.a.set({sessionId:b}));if(this.h.isExpired(this.a.get().sessionId))R(this.a);else if(b=this.a.get()[this.c]||0,a>b&&(100!=a&&100!=b||window.removeEventListener("scroll",this.g),b=a-b,100==a||b>=this.b.increaseThreshold)){var c=
{};this.a.set((c[this.c]=a,c.sessionId=V(this.h),c));a={transport:"beacon",eventCategory:"Max Scroll",eventAction:"increase",eventValue:b,eventLabel:String(a),nonInteraction:!0};this.b.maxScrollMetricIndex&&(a["metric"+this.b.maxScrollMetricIndex]=b);this.f.send("event",x(a,this.b.fieldsObj,this.f,this.b.hitFilter))}};Z.prototype.l=function(a){var b=this;return function(c,d){a(c,d);var e={};("object"==typeof c&&null!==c?c:(e[c]=d,e)).page&&(c=b.c,b.c=Da(b),b.c!=c&&Ea(b))}};
function Da(a){a=t(a.f.get("page")||a.f.get("location"));return a.pathname+a.search}Z.prototype.remove=function(){this.h.j();window.removeEventListener("scroll",this.g);w(this.f,"set",this.l)};B("maxScrollTracker",Z);})();
//# sourceMappingURL=autotrack.custom.js.map